### ISSUE TITLE
how to use handsontable-pro in vue-single-project

### ISSUE THREAD

**Issue by stovd** [handsontable/vue-handsontable-official#11]
hi,
i have a problem by handsontable,how can i use handsontable-pro version in vue-project.
now in my project,i use vue-handsontable-official.but it is Handsontable CE version.i want all function like handsontable-pro.of course,i can buy pro-version,but i want to use in vue-project.thanks.

**Comment by AMBudnik** [comment]
Hi @stovd 

Have you tried to take the steps from the tutorial at https://github.com/handsontable/vue-handsontable-official/wiki/Installation-guide? (PRO configuration at the bottom of the tutorial)

**Comment by TJKoury** [comment]
@AMBudnik I just posted another [issue](https://github.com/handsontable/vue-handsontable-official/issues/19); the problem is that both vue-handsontable-official and handsontable-pro reference 'handsontable', so aliasing 'handsontable' results in handsontable-pro looking to itself for the dependencies.  

The solution could be one of the following:

- Add a vue-handsontable-pro-official that depends on handsontable-pro
- Add some detector logic in this code (probably not a good idea with es5/es6 dynamic import issues)
- Remove all 'handsontable' dependencies in handsontable-pro and make it self-contained

**Comment by jansiegel** [comment]
We made quite a big refactor of the wrapper structure, so it would be easier to configure.
Could you check if installing it as `@handsontable/vue` (or `@handsontable-pro/vue` for the Pro version) fixes your problems?

For more information on how to install it from version `2.0.0-beta1` onwards, see: https://github.com/handsontable/vue-handsontable-official/wiki/Installation-guide

**Comment by mrpiotr-dev** [comment]
I think we can close this issue.
Feel free to reopen if you find the same bug in v2.0.0-beta1+
