### ISSUE TITLE
Adding rows does not update vue instance data correctly

### ISSUE THREAD

**Issue by timwis** [handsontable/vue-handsontable-official#111]
### Description

Adding rows (for example by enabling `minSpareRows` and pressing enter on new rows does not update the data in the vue instance properly. I believe this is because Vue's reactivity system requires you use `Vue.set()` to add new rows to an array. [See details in vue docs here](https://vuejs.org/v2/guide/reactivity.html).

### Demo

https://jsfiddle.net/nqu0oa69/

1. Open the console
2. Type something in the blank row at the end and press enter. Your console should log both the vue instance data and the handsontable instance `getData()` result. They will be identical here.
3. Type something in the _new_ blank row and press enter. Now what's logged will be different: the vue instance data will not know about the new row that was created but the handsontable result will.

### Your environment
* Vue wrapper version: 3.1.0
* Handsontable version: 6.2.2 (community)
* Browser Name and version: firefox
* Operating System: macos

**Comment by AMBudnik** [comment]
Thank you for sharing the demo and description. I believe that this is a matter of reordering the operations. In the first step, the vueData does not see that we have an empty row as well.

**Comment by wojciechczerniak** [comment]
Hi @timwis 

It was you who mentioned that Handsontable isn't flux-style ready, wasn't it? https://github.com/frictionlessdata/delimiter/commit/27fbb5dc8f4450a98202bbcef1f347ecee9b29f6 But we probably should. Changing the prop by reference is a bad idea, there's a `v-model` for that but it's more a syntactic sugar for prop and event.

With Vue.js you provide `settings` and `data` to HotTable component as props and react to events (hooks in Handsontable) to modify the data on change event (`afterChange` hook). We shouldn't modify `data` at all. Whether we should clone the `data` to avoid confusion is an ongoing discussion here: #103, mostly with myself 🙈 Our team agreed internally that Handsontable shouldn't clone the data, that's just how Javascript works and developers should be aware of that. But wrappers can go a step further to fit the framework good practices. I could use another point of view, what do you think?

**Comment by davestewart** [comment]
Hi there,

I've just come across the same issue:

- https://forum.handsontable.com/t/vue-source-data-does-not-seem-to-be-referenced/3248

I see there is ongoing discussion around this.

My opinion on this is that there is nothing wrong with the table updating the data by reference – in fact it makes it a lot easier. What would be useful would be a Vue `@event` to know that this has happened (I don't see any events being emitted when using the table) on the table itself, in this case `@change`.

As mentioned, it could be up to the user to pass in a clone if he wants the data immutable. Or maybe have a flag?

For me, it's quite a common practice to pass data into components and have them update the data, especially for complex objects; see these posts:

- https://forum.vuejs.org/t/pass-object-via-props-reference-vs-emit-value-best-practices/45683/17
- https://forum.vuejs.org/t/data-sync-on-deeply-nested-structures/40099/6

So for now, if I want the data to be updated by HOT, should I just instantiate a normal table and pass the data in?

**Comment by wojciechczerniak** [comment]
Hello @davestewart,

I guess that the discussion has died. Looks like anyone wants to clone the data they can. JS developer is aware how references work in JS and doing it every time would hit the performance so we should leave it like that. Handsontable keeps a lot of meta data next to `data` so relying on this array does not give you all the necessary output. 

You should use our API to retrive what you need and the best way do that is a `callback`.

So the event that you have mentioned is exactly how you should use the wrapper. The reason you haven't find anything emitted is that we don't use `v-on`/`@` events because our `hooks` are slightly different from `events` so they are set as `props` or within `settings` object (this also makes them compatible with vanilla Handsontable). But the idea is the same, use `afterChange` hook/event/callback to handle changes.

This fits Vue philosophy of communication between components. Data is passed to the children through observable `attributes` and the parent is notified about changes through `callbacks`.

**Comment by davestewart** [comment]
Ah, function props, OK, I'll plug that in, thanks.

**Comment by davestewart** [comment]
I also found that resetting the data using the `Vue.set()` technique as mentioned by @timwis kills the table's undo stack.

I tested this in JS Fiddle and my guess is that it is using `hot.loadData()` which seems to have the same result.

So I guess, as you say, once data has gone into the table, just use the API.

This being the case, I'm wondering how much value there is to wrapping this for vue. Looking at the source, it is very simple. It might be worth explaining this in the description, that is is NOT a Vue component as such, merely a convenience wrapper and there are caveats, especially concerning data lifecycle.
