### ISSUE TITLE
How can I use getData() with HotTable component?

### ISSUE THREAD

**Issue by thanatva** [handsontable/vue-handsontable-official#14]
Hi,

If I want to use [getData()](https://docs.handsontable.com/0.16.1/Core.html#getData) method of Handsontable from this component, how can I use it?

Template
```
<no-ssr placeholder="loading...">
     <hot-table :root="root" :settings="hotSettings"></hot-table>
</no-ssr>
```

Script

```
export default {
    components: {
      'no-ssr': NoSSR
    },
    data () {
      return {
        root: 'test-hot',
        hotSettings: {
          data: [['a', 'ab'], ['cd', 'eg']],
          colHeaders: true
        },        
      }
    },   
  }
```

Note: I'm using Nuxt.js and register HotTable as Vue component inside a plugin

**Comment by TJKoury** [comment]
Add an 'afterChange' (or whatever) event hook.  Inside each event hook the 'this' keyword is the instance of the table.  There's probably another more programmatic way to do it by getting the component instance directly [like this](https://github.com/handsontable/vue-handsontable-official/issues/7), but this is what I'm working with, especially because you want to get the data after it changes, instead of having some race condition between Vue and HOT.


```
export default {
    components: {
      'no-ssr': NoSSR
    },
    data () {
      return {
        root: 'test-hot',
        hotSettings: {
          data: [['a', 'ab'], ['cd', 'eg']],
          colHeaders: true,
          afterChange: function () { 
              console.log(this.getData()) 
          }
        },        
      }
    },   
  }
```

**Comment by mrpiotr-dev** [comment]
Hi @Slasher154,
Here is an example: https://codepen.io/swistach/pen/XqBWQx
