### ISSUE TITLE
Numeric / Currency formatting

### ISSUE THREAD

**Issue by grund3g** [handsontable/vue-handsontable-official#35]
Hi,

is there anything I'm missing when using a numeric format for cells? (as described here: [https://docs.handsontable.com/0.35.1/demo-numeric.html](https://docs.handsontable.com/0.35.1/demo-numeric.html))

Should I also include https://docs.handsontable.com/0.35.1/bower_components/numbro/dist/languages.min.js?

**Comment by AMBudnik** [comment]
Hi @grund3g 

We would need to investigate this case. It looks like the wrapper does not accept the external _languages_ file and is able to handle only `en-US` currency.

**Comment by dshinton-qstart** [comment]
I am having the same issue. Here is a demo which shows number formatting is not working.

https://codepen.io/anon/pen/EEOoWK

**Comment by AMBudnik** [comment]
Hm... I do not know why but I cannot see anything loading incorrectly in your demo. They seem to have the same resources and logic as this one https://codepen.io/anon/pen/xWmLeg where `type: numeric` works well.

**Comment by dshinton-qstart** [comment]
There is a big difference in the examples. Using an array of arrays (such as your example) works. Using an array of objects and column definitions using the "data" property breaks validation.

So that is the workaround for now. I will convert my project to use arrays of arrays instead of objects with keys.

**Comment by AMBudnik** [comment]
You're right. When I convert it to an object that uses `data` parameter of the columns record the validation does not occur: https://codepen.io/anon/pen/ZxVMqE?editors=0010 If I do not use `data` for `columns` settings the cell is validated.

Thanks for spotting that @dshinton-qstart 

ps. I think that we should open a new issue for the `data` topic. This issue is more for the `languages` conversion.

**Comment by mrpiotr-dev** [comment]
Hi @grund3g, @dshinton-qstart 
In UMD (as on Codepen) you can load languages as in my example: https://codepen.io/swistach/pen/jxxMBd
But if you try to use `numbro` + cultures in a project created eg. by vue-cli, then, unfortunately, you will get an error with unknown culture.
You can follow progress here: handsontable/handsontable#5081

**Comment by mrpiotr-dev** [comment]
It should work in Handsontable v4+. If you find a similar problem with languages/formatting in our wrapper, then feel free to reopen this issue.
