### ISSUE TITLE
Cannot find module 'pikaday'

### ISSUE THREAD

**Issue by iuphero** [handsontable/vue-handsontable-official#6]
I use webpack2.
Error is `Cannot find module 'pikaday'`

**Comment by robarchibald** [comment]
I ran into this as well, only mine was complaining about numbro. See issue #2 for my proposed update to the wiki for webpack2. After I made the change, it works for me.

**Comment by jansiegel** [comment]
@happyhero0, @robarchibald, could you try updating to the latest version and see if it's still a problem? Since version `1.0.0` all the Handsontable dependencies should be imported automatically, please see the current installation instructions: https://github.com/handsontable/vue-handsontable-official/wiki/Installation-guide#basic-installation

**Comment by mrpiotr-dev** [comment]
I think we can close this issue.
Feel free to reopen if it still occurs.
